server:
  port: 9080
  servlet:
    context-path: /tender-api

spring:
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
springfox:
  documentation:
    swagger-ui:
      enabled: false
    swagger:
      v2:
        enabled: false
